#!/bin/bash
# install.sh — Vault Watcher one-click installer
# Called by the skill with pre-filled configuration variables.
#
# Required env vars (set by the skill before calling):
#   VW_VAULT_ROOT    — Obsidian vault absolute path
#   VW_WATCH_DIRS    — Colon-separated watch dirs (relative to vault root)
#   VW_ARCHIVE_DIR   — Archive dir (relative to vault root)
#   VW_DIFF_TARGET   — Diff-tracked file (relative to vault root, empty to disable)
#   VW_APP_ID        — Feishu App ID
#   VW_APP_SECRET    — Feishu App Secret
#   VW_CHAT_ID       — Feishu Chat ID
#   VW_API_BASE      — Feishu API base (default: https://open.feishu.cn)
#   VW_INSTALL_DIR   — Install directory (default: ~/.vault-watcher)
#   VW_LABEL         — launchd label (default: com.vault-watcher)

set -euo pipefail

INSTALL_DIR="${VW_INSTALL_DIR:-$HOME/.vault-watcher}"
LABEL="${VW_LABEL:-com.vault-watcher}"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
API_BASE="${VW_API_BASE:-https://open.feishu.cn}"

echo "🚀 Installing Vault Watcher..."
echo "   Vault:   $VW_VAULT_ROOT"
echo "   Install: $INSTALL_DIR"

# 1. Check macOS TCC / Full Disk Access (needed for iCloud-synced vaults)
if [[ "$VW_VAULT_ROOT" == *"Mobile Documents"* ]] || [[ "$VW_VAULT_ROOT" == *"iCloud"* ]]; then
  echo "⚠️  Vault 位于 iCloud Drive，Diff 追踪功能需要 Full Disk Access 权限。"
  echo "   请确保已将 /bin/bash 添加到：系统设置 > 隐私与安全性 > 完全磁盘访问权限"
  echo "   (文件变更检测不受影响，仅 diff 内容展示需要此权限)"
  echo ""

  TEST_FILE=$(find "$VW_VAULT_ROOT" -maxdepth 2 -name "*.md" -type f 2>/dev/null | head -1)
  if [ -n "$TEST_FILE" ]; then
    if ! cat "$TEST_FILE" > /dev/null 2>&1; then
      echo "❌ 权限验证失败：无法读取 $TEST_FILE"
      echo "   请先在 系统设置 > 隐私与安全性 > 完全磁盘访问权限 中添加 /bin/bash"
      exit 1
    fi
  fi
fi

# 2. Check fswatch
if ! command -v fswatch &>/dev/null; then
  if command -v brew &>/dev/null; then
    echo "📦 Installing fswatch via Homebrew..."
    brew install fswatch
  else
    echo "❌ fswatch not found. Install: brew install fswatch"
    exit 1
  fi
fi
FSWATCH_PATH="$(command -v fswatch)"
echo "✅ fswatch: $FSWATCH_PATH"

# 3. Create install directory
mkdir -p "$INSTALL_DIR/logs"
echo "✅ Directory: $INSTALL_DIR"

# 4. Build WATCH_DIRS array string for bash script
IFS=':' read -ra DIRS <<< "$VW_WATCH_DIRS"
WATCH_DIRS_BASH=""
for d in "${DIRS[@]}"; do
  WATCH_DIRS_BASH+="  \"\${VAULT_ROOT}/${d}\"\n"
done

# 5. Generate vault-watcher.sh
DIFF_LINE=""
if [ -n "${VW_DIFF_TARGET:-}" ]; then
  DIFF_LINE="DIFF_TARGET=\"\${VAULT_ROOT}/${VW_DIFF_TARGET}\""
else
  DIFF_LINE="DIFF_TARGET=\"\""
fi

cat > "$INSTALL_DIR/vault-watcher.sh" << 'WATCHER_SCRIPT_HEADER'
#!/bin/bash
# vault-watcher.sh — Auto-generated by Vault Watcher Skill
# Obsidian Vault file change monitor with Feishu/Lark notifications
# Compatible with macOS built-in bash 3.2

WATCHER_SCRIPT_HEADER

cat >> "$INSTALL_DIR/vault-watcher.sh" << WATCHER_CONFIG
VAULT_ROOT="$VW_VAULT_ROOT"
WATCH_DIRS=(
$(echo -e "$WATCH_DIRS_BASH"))
ARCHIVE_DIR="\${VAULT_ROOT}/$VW_ARCHIVE_DIR"
DEBOUNCE_SEC=10
LOG_DIR="$INSTALL_DIR/logs"
NOTIFY_SCRIPT="\$(dirname "\$0")/vault-notify.py"
$DIFF_LINE
DIFF_SHADOW="\${LOG_DIR}/vault-watcher-todo-shadow.md"
WATCHER_CONFIG

cat >> "$INSTALL_DIR/vault-watcher.sh" << 'WATCHER_BODY'

BATCH_FILE="/tmp/vault-watcher-batch.txt"
LOCK_FILE="/tmp/vault-watcher.lock"
LOG_FILE="${LOG_DIR}/vault-watcher.log"
SNAPSHOT_FILE="${LOG_DIR}/vault-watcher-snapshot.txt"
DIFF_OUTPUT="/tmp/vault-watcher-diff.txt"

mkdir -p "$LOG_DIR"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG_FILE"; }

should_ignore() {
  local path="$1"
  case "$path" in
    *.icloud) return 0 ;; *~) return 0 ;; *.tmp) return 0 ;;
    */.DS_Store) return 0 ;; */.obsidian/*) return 0 ;;
  esac
  local base; base="$(basename "$path")"
  case "$base" in .*) return 0 ;; esac
  return 1
}

relative_path() { echo "${1#$VAULT_ROOT/}"; }

generate_diff() {
  rm -f "$DIFF_OUTPUT"
  [ -z "$DIFF_TARGET" ] && return
  [ ! -f "$DIFF_TARGET" ] && return
  if [ ! -f "$DIFF_SHADOW" ]; then
    cp "$DIFF_TARGET" "$DIFF_SHADOW" 2>/dev/null; return
  fi
  local raw; raw=$(diff -u "$DIFF_SHADOW" "$DIFF_TARGET" 2>/dev/null)
  if [ -n "$raw" ]; then echo "$raw" > "$DIFF_OUTPUT"; fi
  if ! cp "$DIFF_TARGET" "$DIFF_SHADOW" 2>/dev/null; then
    log "WARN: shadow update failed (check Full Disk Access for /bin/bash)"
  fi
}

flush_batch() {
  [ ! -f "$BATCH_FILE" ] && return
  [ ! -s "$BATCH_FILE" ] && { rm -f "$BATCH_FILE"; return; }
  if ! mkdir "$LOCK_FILE" 2>/dev/null; then return; fi

  local tmp_sorted="/tmp/vault-watcher-sorted.txt"
  sort -u "$BATCH_FILE" > "$tmp_sorted"; rm -f "$BATCH_FILE"

  local new_items="" modified_items="" archived_items="" deleted_items=""
  local new_count=0 modified_count=0 archived_count=0 deleted_count=0
  local diff_triggered=0

  while IFS= read -r full_path; do
    [ -z "$full_path" ] && continue; [ -d "$full_path" ] && continue
    local rel; rel=$(relative_path "$full_path")
    local base; base="$(basename "$full_path")"

    if [ -e "$full_path" ]; then
      if [ -f "$SNAPSHOT_FILE" ] && grep -qF "$full_path" "$SNAPSHOT_FILE"; then
        modified_count=$((modified_count + 1))
        [ -z "$modified_items" ] && modified_items="\"${rel}\"" || modified_items="${modified_items},\"${rel}\""
        [ "$full_path" = "$DIFF_TARGET" ] && diff_triggered=1
      else
        new_count=$((new_count + 1))
        [ -z "$new_items" ] && new_items="\"${rel}\"" || new_items="${new_items},\"${rel}\""
        echo "$full_path" >> "$SNAPSHOT_FILE"
      fi
    elif [ -e "${ARCHIVE_DIR}/${base}" ]; then
      archived_count=$((archived_count + 1))
      local src_dir; src_dir=$(dirname "$rel")
      [ -z "$archived_items" ] && archived_items="\"${base}|${src_dir}\"" || archived_items="${archived_items},\"${base}|${src_dir}\""
      if [ -f "$SNAPSHOT_FILE" ]; then
        grep -vF "$full_path" "$SNAPSHOT_FILE" > "${SNAPSHOT_FILE}.tmp" 2>/dev/null
        mv "${SNAPSHOT_FILE}.tmp" "$SNAPSHOT_FILE" 2>/dev/null
      fi
    else
      deleted_count=$((deleted_count + 1))
      [ -z "$deleted_items" ] && deleted_items="\"${rel}\"" || deleted_items="${deleted_items},\"${rel}\""
      if [ -f "$SNAPSHOT_FILE" ]; then
        grep -vF "$full_path" "$SNAPSHOT_FILE" > "${SNAPSHOT_FILE}.tmp" 2>/dev/null
        mv "${SNAPSHOT_FILE}.tmp" "$SNAPSHOT_FILE" 2>/dev/null
      fi
    fi
  done < "$tmp_sorted"

  rm -f "$tmp_sorted"; rmdir "$LOCK_FILE" 2>/dev/null
  local total=$((new_count + modified_count + archived_count + deleted_count))
  [ $total -eq 0 ] && return

  [ $diff_triggered -eq 1 ] && generate_diff
  local title="📂 Vault 变更 · $(date '+%H:%M') · ${total} 项"
  local diff_arg=""
  [ -f "$DIFF_OUTPUT" ] && [ -s "$DIFF_OUTPUT" ] && diff_arg="$DIFF_OUTPUT"

  python3 "$NOTIFY_SCRIPT" "$title" "[${new_items}]" "[${modified_items}]" "[${archived_items}]" "[${deleted_items}]" "$diff_arg" 2>> "$LOG_FILE" && \
    log "Pushed: ${total} (new=${new_count} mod=${modified_count} arch=${archived_count} del=${deleted_count} diff=${diff_triggered})" || \
    log "ERROR: notify failed"
  rm -f "$DIFF_OUTPUT"
}

process_path() {
  local path="$1"; should_ignore "$path" && return; [ -d "$path" ] && return
  echo "$path" >> "$BATCH_FILE"
}

log "vault-watcher started. Watching: ${WATCH_DIRS[*]}"

if [ ! -f "$SNAPSHOT_FILE" ] || [ ! -s "$SNAPSHOT_FILE" ]; then
  log "Building initial file snapshot..."
  rm -f "$SNAPSHOT_FILE"
  for d in "${WATCH_DIRS[@]}"; do find "$d" -type f 2>/dev/null >> "$SNAPSHOT_FILE"; done
  sort -o "$SNAPSHOT_FILE" "$SNAPSHOT_FILE"
  log "Snapshot built: $(wc -l < "$SNAPSHOT_FILE") files indexed"
fi

if [ -n "$DIFF_TARGET" ] && [ ! -f "$DIFF_SHADOW" ] && [ -f "$DIFF_TARGET" ]; then
  cp "$DIFF_TARGET" "$DIFF_SHADOW"
  log "Diff shadow initialized for: $(basename "$DIFF_TARGET")"
fi

FSWATCH_BIN=$(command -v fswatch || echo /opt/homebrew/bin/fswatch)
"$FSWATCH_BIN" --recursive --latency 8 \
  --exclude '\.icloud$' --exclude '~$' --exclude '\.tmp$' \
  --exclude '\.DS_Store' --exclude '/\.' \
  "${WATCH_DIRS[@]}" | while IFS= read -r path; do
  if [ -n "$path" ]; then
    process_path "$path"
    [ -f /tmp/vault-watcher-flush.pid ] && kill "$(cat /tmp/vault-watcher-flush.pid)" 2>/dev/null || true
    ( sleep "$DEBOUNCE_SEC" && flush_batch ) &
    echo $! > /tmp/vault-watcher-flush.pid
  fi
done
WATCHER_BODY

chmod +x "$INSTALL_DIR/vault-watcher.sh"
echo "✅ Generated: vault-watcher.sh"

# 6. Generate vault-notify.py
cat > "$INSTALL_DIR/vault-notify.py" << NOTIFY_HEADER
#!/usr/bin/env python3
"""vault-notify.py — Auto-generated by Vault Watcher Skill"""
import json, os, re, sys, urllib.request
from datetime import datetime

APP_ID = "$VW_APP_ID"
APP_SECRET = "$VW_APP_SECRET"
CHAT_ID = "$VW_CHAT_ID"
API_BASE = "$API_BASE"
NOTIFY_HEADER

cat >> "$INSTALL_DIR/vault-notify.py" << 'NOTIFY_BODY'

def get_token():
    data = json.dumps({"app_id": APP_ID, "app_secret": APP_SECRET}).encode()
    req = urllib.request.Request(
        f"{API_BASE}/open-apis/auth/v3/tenant_access_token/internal",
        data=data, headers={"Content-Type": "application/json"})
    resp = json.loads(urllib.request.urlopen(req, timeout=10).read())
    return resp.get("tenant_access_token", "")

def parse_diff(diff_path):
    if not diff_path or not os.path.isfile(diff_path): return None
    with open(diff_path, "r", encoding="utf-8") as f: lines = f.readlines()
    added, removed = [], []
    for line in lines:
        if line.startswith("+++") or line.startswith("---"): continue
        if line.startswith("+"): c = line[1:].strip(); c and added.append(c)
        elif line.startswith("-"): c = line[1:].strip(); c and removed.append(c)
    if not added and not removed: return None
    return {"added": added, "removed": removed, "added_count": len(added), "removed_count": len(removed)}

def clean_line(line):
    s = re.sub(r'^- \[[ x]\] ', '', line.strip()).replace('**', '')
    return re.sub(r'\[\[.*?\]\]', '', s).strip()

def format_diff_section(dd, label="tracked file"):
    if not dd: return ""
    parts = [f"**📋 {label} · 变更详情**", f"`+{dd['added_count']}行 / -{dd['removed_count']}行`\n"]
    for l in dd["added"][:6]:
        c = clean_line(l); c and parts.append(f"🟢 {c}")
    if dd["added_count"] > 6: parts.append(f"  …及另 {dd['added_count'] - 6} 行")
    if dd["removed"]:
        dd["added"] and parts.append("")
        for l in dd["removed"][:4]:
            c = clean_line(l); c and parts.append(f"🔴 ~~{c}~~")
        if dd["removed_count"] > 4: parts.append(f"  …及另 {dd['removed_count'] - 4} 行")
    return "\n".join(parts)

def build_card(title, new, mod, arch, deleted, dd=None):
    elems, n = [], 0
    if new:
        lines = [f"• `{f}`" for f in new[:6]]
        len(new) > 6 and lines.append(f"• ...及另 {len(new)-6} 个")
        elems.append({"tag": "markdown", "content": f"**➕ New ({len(new)})**\n" + "\n".join(lines)}); n += 1
    if mod:
        lines = [f"• `{f}`" for f in mod[:6]]
        len(mod) > 6 and lines.append(f"• ...及另 {len(mod)-6} 个")
        n > 0 and elems.append({"tag": "hr"})
        elems.append({"tag": "markdown", "content": f"**✏️ Modified ({len(mod)})**\n" + "\n".join(lines)}); n += 1
    if arch:
        lines = []
        for i in arch[:5]:
            if "|" in i: fn, sd = i.split("|", 1); lines.append(f"• `{fn}`\n  ↳ {sd}/ → archive/")
            else: lines.append(f"• `{i}` → archive/")
        len(arch) > 5 and lines.append(f"• ...及另 {len(arch)-5} 个")
        n > 0 and elems.append({"tag": "hr"})
        elems.append({"tag": "markdown", "content": f"**📦 Archived ({len(arch)})**\n" + "\n".join(lines)}); n += 1
    if deleted:
        lines = [f"• ~~`{f}`~~" for f in deleted[:5]]
        len(deleted) > 5 and lines.append(f"• ...及另 {len(deleted)-5} 个")
        n > 0 and elems.append({"tag": "hr"})
        elems.append({"tag": "markdown", "content": f"**🗑️ Deleted ({len(deleted)})**\n" + "\n".join(lines)}); n += 1
    if dd:
        dm = format_diff_section(dd); dm and (elems.append({"tag": "hr"}), elems.append({"tag": "markdown", "content": dm}))
    elems.append({"tag": "hr"})
    elems.append({"tag": "note", "elements": [{"tag": "plain_text", "content": f"⏱️ {datetime.now().strftime('%H:%M:%S')} · Vault Watcher · launchd"}]})
    return {"header": {"title": {"tag": "plain_text", "content": title}, "template": "wathet"}, "elements": elems}

def send(title, new, mod, arch, deleted, dd=None):
    token = get_token()
    if not token: print("ERROR: no token", file=sys.stderr); return False
    card = build_card(title, new, mod, arch, deleted, dd)
    payload = {"receive_id": CHAT_ID, "msg_type": "interactive", "content": json.dumps(card)}
    req = urllib.request.Request(
        f"{API_BASE}/open-apis/im/v1/messages?receive_id_type=chat_id",
        data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"})
    resp = json.loads(urllib.request.urlopen(req, timeout=10).read())
    if resp.get("code") != 0: print(f"ERROR: {resp}", file=sys.stderr); return False
    return True

if __name__ == "__main__":
    if len(sys.argv) < 3: print(__doc__, file=sys.stderr); sys.exit(1)
    title = sys.argv[1]
    new = json.loads(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[2] else []
    mod = json.loads(sys.argv[3]) if len(sys.argv) > 3 and sys.argv[3] else []
    arch = json.loads(sys.argv[4]) if len(sys.argv) > 4 and sys.argv[4] else []
    deleted = json.loads(sys.argv[5]) if len(sys.argv) > 5 and sys.argv[5] else []
    dp = sys.argv[6] if len(sys.argv) > 6 and sys.argv[6] else None
    dd = parse_diff(dp) if dp else None
    ok = send(title, new, mod, arch, deleted, dd)
    sys.exit(0 if ok else 1)
NOTIFY_BODY

chmod +x "$INSTALL_DIR/vault-notify.py"
echo "✅ Generated: vault-notify.py"

# 7. Generate launchd plist
cat > "$PLIST" << PLIST_CONTENT
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${INSTALL_DIR}/vault-watcher.sh</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>/tmp/vault-watcher-stdout.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/vault-watcher-stderr.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
</dict>
</plist>
PLIST_CONTENT

echo "✅ Generated: $PLIST"

# 8. Load launchd service
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
echo "✅ Service loaded: $LABEL"

# 9. Verify
sleep 2
if launchctl list | grep -q "$LABEL"; then
  echo ""
  echo "🎉 Vault Watcher 安装完成！"
  echo "   服务已启动，约 18 秒内变更将推送到飞书。"
  echo "   日志: $INSTALL_DIR/logs/vault-watcher.log"
else
  echo "⚠️ Service may not have started. Check: launchctl list | grep vault-watcher"
fi
